name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - run: dotnet restore test1
    - run: dotnet build --no-restore test1
    - run: dotnet test --no-build --verbosity normal test1
